### ISSUE TITLE
Tempora only compatible with SeuratV2

### ISSUE THREAD

**Issue by DustinSokolowski** [BaderLab/Tempora#1]
Seurat has had a massive update in the last few months (v3). Tempora only accommodates Seurat V2. Unfortunately, the objects in each package have some pretty fundamental differences to one another and the "ImportSeuratObject" function does not work. I think that a ImportSeuratV3Object compatible with Tempora would be highly valuable to working with scRNA-seq data processed since 2019.

**Comment by innesbre** [comment]
This should hopefully be addressed with my pull request.
