### ISSUE TITLE
Error: object 'gams' not found in PlotVaryingPWs()

### ISSUE THREAD

**Issue by kevincjnixon** [BaderLab/Tempora#10]
Hello.

When running PlotVaryingPWs(), I was running into the error: object 'gams' not found. I went back through the code and found that the GAMs were calculated, but not stored in IdentifyVaryingPWs(). As a result, the GAMs were not provided for PlotVaryingPWs(). 

I came up with a quick fix around this by having IdentifyVaryingPWs() return a list with the Tempora object and the gams, and then inputting the gams into PlotVaryingPWs(), however it might be ideal to create a slot in the Tempora object for the gams which can be recalled in PlotVaryingPWs().

Thanks!

**Comment by thinh-tran** [comment]
Hi! Thanks for bringing this to my attention and apology for the oversight. I added a `gams` slot that can store the calculated GAMs, which can be accessed at `object@gams.` PlotVaryingPWs is now also points to this data.
