### ISSUE TITLE
GSVA version

### ISSUE THREAD

**Issue by baj12** [BaderLab/Tempora#18]
it seems that GSVA needs to be at least 1.38.2 (1.38.1 wasn't working, I found references to version 1.38.2 that should be working, I haven't tested 1.38.2, but I am now working with 1.39.17 and that works)

**Comment by risserlin** [comment]
I am using GSVA 1.36.3 with no issues.  Maybe it is an issue specific to 1.38.1.  What error did you get?

**Comment by baj12** [comment]
sorry, I already switched and don't remember.
