### ISSUE TITLE
GSVA parallel.sz argument throws error

### ISSUE THREAD

**Issue by innesbre** [BaderLab/Tempora#2]
Leaving `CalculatePWProfiles(...,parallel.sz=NULL)` (the default) causes an error when method is set to GSVA because it expects an integer (NULL breaks the logical arguments they use to evaluate number of cores to assign).  Not sure how to make GSVA not operate in parallel, since setting it to FALSE yielded the same behaviour as setting it to 0 (GSVA default) - all available cores were used.

**Comment by thinh-tran** [comment]
You can set `parallel.sz=1` to stop GSVA from doing the analysis in parallel (this is now the default). I have updated the documentation of the CalculatePWProfiles function and change the default from NULL to 1. Thank you for catching this!
