### ISSUE TITLE
Cannot download example MouseCortex Rdata

### ISSUE THREAD

**Issue by hk20013106** [BaderLab/Tempora#21]
Hi,

I tried download the Rdata several times using different browsers, computers, systems.
They all tucked at about 669.6MB. 
Any thought or idea will be of great help!

trying URL 'https://www.baderlab.org/Software/Tempora?action=AttachFile&do=get&target=MouseCortex.RData'
Content type 'application/octet-stream' length 1019681258 bytes (972.4 MB)
downloaded 669.6 MB

Warning message:
In download.file(paste(data_url, data_file, sep = ""), destfile = dest_data_file) :
  downloaded length 702083017 != reported length 1019681258

**Comment by risserlin** [comment]
It is working for me from a web browser.  

I have uploaded it to our download server as well if you want to see if that fixes your issue:
http://download.baderlab.org/tempora/Mousecortex.RData

**Comment by hk20013106** [comment]
> It is working for me from a web browser.
> 
> I have uploaded it to our download server as well if you want to see if that fixes your issue: http://download.baderlab.org/tempora/Mousecortex.RData

Many thanks for your quick reply. The newly uploaded file on your server works for me!
