### ISSUE TITLE
Error in CalculatePWProfiles due to GSEABase::getGmt

### ISSUE THREAD

**Issue by zandigohar** [BaderLab/Tempora#22]
To estimate pathway enrichment profiles of clusters, I was trying to run `CalculatePWProfiles` on a dataset and got into an error. 

After reading the R code in `CalculatePWProfiles`, I realized the actual issue is with `pathwaygmt <- GSEABase::getGmt(gmt_file, sep = "\t")` which apparently does not have anything to do with a user's input data. 

The screenshot of my console, including the GSEA version, gmt file name, and the error message is as below:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/36520735/168505130-6aeca09c-1c9e-475d-86ac-158e573d8254.png">
R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)

Are there any workarounds for this? I highly appreciate any help.

**Comment by zandigohar** [comment]
I downloaded an earlier version of gmt file (May 5th instead of May 12th) and it worked! So I am closing this. Not sure why the latest version throws issues.

**Comment by risserlin** [comment]
Thanks for reporting.  It looks like there are a bunch of pathways coming from some of the databases that don't have names and the paxtools parser is giving them all the name "OTHER".
