### ISSUE TITLE
Error in BuildTrajectory

### ISSUE THREAD

**Issue by eflynnFive** [BaderLab/Tempora#23]
Hello, I am getting a strange error in BuildTrajectory with my dataset. Here is the error traceback:

Error in `$<-.data.frame`(`*tmp*`, "from_clusterscore", value = c(NA_real_, : replacement has 18 rows, data has 38

4 stop(sprintf(ngettext(N, "replacement has %d row, data has %d", "replacement has %d rows, data has %d"), N, nrows), domain = NA)

3 `$<-.data.frame`(`*tmp*`, "from_clusterscore", value = structure(c(NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, ...

2 `$<-`(`*tmp*`, "from_clusterscore", value = structure(c(NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, NA_real_, ...

1 BuildTrajectory(stromal_tempora, n_pcs = 6, difference_threshold = 0.01)

It appears to be an error involving dataframe assignment, but I could not determine where in BuildTrajectory.R that issue might arise. I can also send you along my Seurat Object as well as my Tempora object if that helps. It is an integrated dataset.

Best,
Emmet Flynn

**Comment by thinh-tran** [comment]
Hi Emmet,

If you could send along your seurat object and your tempora object, that would be great! If they're large files, you can put them on Google Drive and share them with me at [tt1091@nyu.edu](url).

**Comment by eflynnFive** [comment]
Thinh, 

I just shared with you the objects on Google Drive.

Also, the command I used to create the tempora object is as follows:

stromal_tempora <- ImportSeuratObject(fixed.stromal, clusters="Zebrafish.cluster",
    assaySlot="data",
    timepoints="TIME",
    assayType="integrated",
    timepoint_order=c("Three", "Five"))

Thanks.

**Comment by eflynnFive** [comment]
I figured out the issue. The "clusters" chosen for the tempora object cannot be strings, they have to be numbers.
