### ISSUE TITLE
Error in IdentifyVaryingPWs()

### ISSUE THREAD

**Issue by Pestudkaru** [BaderLab/Tempora#5]
Hi! 
I get the same error with both the tutorial mouse data set and also with my own data. 
Error in IdentifyVaryingPWs(cortex_tempora, pval_threshold = 0.05) : 
  object 'plot_df' not found

Also in the CalculatePWProfiles() function the part with parallelization "parallel.sz = DetectCores()-2)" has changed for some reason to detectCores(). Maybe between update 3.6.2 and 3.6.3 they changed the capitalization.

**Comment by thinh-tran** [comment]
Hi! This was an issue with some special characters in the pathways' names that I didn't account for. I updated the function to take care of these special cases and that should fix it - can you try again?

Thanks for pointing out the case change in detectCores() - I'll update the vignette.

**Comment by Pestudkaru** [comment]
Hi!
So now I get an error already at the first step: ImportSeuratObject() 
Extracting data...
Extracting metadata...
Creating Tempora object...Error in CreateTemporaObject(data, meta.data = metadata, timepoint_order = timepoint_order,  : 
  object 'celltype_markers' not found
And again it happens both with my data and with the mouse cortex data.

**Comment by thinh-tran** [comment]
ImportSeuratObject() now takes a `celltype_markers` parameter to perform automated cluster labeling in case the clusters are not already labeled - I documented this in the manual page of the function but haven't yet written it up on the main GitHub page, sorry about the confusion! In your case, you can pass `celltype_markers = NULL` to ImportSeuratObject() and that'll take care of it.

**Comment by zhangjiaobxy** [comment]
Hello,
I got the same error in IdentifyVaryingPWs() as below: 
```
> cortex_tempora <- IdentifyVaryingPWs(cortex_tempora, pval_threshold = 0.05)
Fitting GAM models...Error in IdentifyVaryingPWs(cortex_tempora, pval_threshold = 0.05) : 
  object 'plot_df' not found
```

I am using the tutorial MouseCortex.RData data. I am using Mouse_GOBP_AllPathways_no_GO_iea_April_01_2020_symbol.gmt in function CalculatePWProfiles(), because I can not find the Mouse_GOBP_AllPathways_no_GO_iea_September_01_2019_symbol.gmt file on the website (http://download.baderlab.org/EM_Genesets/current_release/).

Any help will be appreciated, thanks a lot!
