### ISSUE TITLE
Problem with IdentifyVaryingPWs

### ISSUE THREAD

**Issue by DustinSokolowski** [BaderLab/Tempora#8]
Hello!

When running the Tempora workflow, we found an error in the IdentifyVaryingPWs function. In the for loop on line 41, there is no option for when  themes[i] is not in rownames(gsva_bycluster) (or length(grep(themes[i], rownames(gsva_bycluster))) == 0).

I remade the function locally and added: the following code which helped:    if(length(grep(themes[i], rownames(gsva_bycluster))) == 0) {
      p_vals[[i]] <- 1
      gams[[i]] <- "no_gam_available"
      next
    }

Best!
Dustin

**Comment by DustinSokolowski** [comment]
oops
``   
 if(length(grep(themes[i], rownames(gsva_bycluster))) == 0) {
      p_vals[[i]] <- 1
      gams[[i]] <- "no_gam_available"
      next
    }
``

**Comment by thinh-tran** [comment]
Hi Dustin! Thanks for bringing this to my attention and sorry for the late response. I have fixed the loop now as suggested.
