### ISSUE TITLE
Error: object 'plot_df' not found in IdentifyVaryingPWs()

### ISSUE THREAD

**Issue by zhangjiaobxy** [BaderLab/Tempora#9]
Hello,
I got an error of object 'plot_df' not found in IdentifyVaryingPWs() as below:

```
> cortex_tempora <- IdentifyVaryingPWs(cortex_tempora, pval_threshold = 0.05)
Fitting GAM models...Error in IdentifyVaryingPWs(cortex_tempora, pval_threshold = 0.05) : 
  object 'plot_df' not found
```
I am using the tutorial MouseCortex.RData data. I am using Mouse_GOBP_AllPathways_no_GO_iea_April_01_2020_symbol.gmt in function CalculatePWProfiles(), because I can not find the Mouse_GOBP_AllPathways_no_GO_iea_September_01_2019_symbol.gmt file on the website (http://download.baderlab.org/EM_Genesets/current_release/).

Any help will be appreciated, thanks a lot!

**Comment by risserlin** [comment]
not sure if I can help with the running error but you can find the gmt file specified in this directory:
http://download.baderlab.org/EM_Genesets/September_01_2019/Mouse/symbol/

here is a link to the file:
http://download.baderlab.org/EM_Genesets/September_01_2019/Mouse/symbol/Mouse_GOBP_AllPathways_no_GO_iea_September_01_2019_symbol.gmt

**Comment by zhangjiaobxy** [comment]
Thanks for your help! 

I tried this file (Mouse_GOBP_AllPathways_no_GO_iea_September_01_2019_symbol.gmt) as described in the tutorial. But I still get the same error for one of my datasets. 
However, `IdentifyVaryingPWs()` works for some of the datasets. Does that error indicate there is no varying pathways detected, so the code can't plot any figure?

**Comment by thinh-tran** [comment]
Hi! My apology for the late response. The error you received can be due to Tempora not detecting any varying pathways as you said. I have fixed the error messages so that it's clearer if this happens.
